//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_WEB.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCarrito
    {
        public int Consecutivo { get; set; }
        public int ConsecutivoUsuario { get; set; }
        public int ConsecutivoServicio { get; set; }
        public System.DateTime FechaHoraCarrito { get; set; }
        public int ConsecutivoHorario { get; set; }
        public int Estado { get; set; }
    
        public virtual tServicio tServicio { get; set; }
        public virtual tUsuario tUsuario { get; set; }
    }
}
