//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_WEB.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHorario
    {
        public int Consecutivo { get; set; }
        public int ConsecutivoServicio { get; set; }
        public System.DateTime FechaDisponible { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFin { get; set; }
    
        public virtual tServicio tServicio { get; set; }
    }
}
