//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_WEB.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUsuario
    {
        public int Consecutivo { get; set; }
        public string Identificacion { get; set; }
        public string Contrasenna { get; set; }
        public string Nombre { get; set; }
        public string CorreoElectronico { get; set; }
        public int Estado { get; set; }
        public int ConsecutivoRol { get; set; }
        public string ImagenUsuario { get; set; }
    
        public virtual tRol tRol { get; set; }
    }
}
